const cards = [
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "mockingbird", min: 5, max: 7 },
  { name: "flamingo", min: 2, max: 3 },
  { name: "flamingo", min: 2, max: 3 },
  { name: "flamingo", min: 2, max: 3 },
  { name: "flamingo", min: 2, max: 3 },
  { name: "flamingo", min: 2, max: 3 },
  { name: "flamingo", min: 2, max: 3 },
  { name: "flamingo", min: 2, max: 3 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "parrot", min: 4, max: 6 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "tucan", min: 3, max: 4 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "large", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "bird", min: 6, max: 9 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "duck", min: 4, max: 6 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 },
  { name: "owl", min: 3, max: 4 }
]

function shuffleCards(deck) {
  if (!deck) return undefined

  for (let i = 0; i < deck.length; i++) {
    const num = Math.floor(Math.random() * i)
    const tempArray = deck[i]
    deck[i] = deck[num]
    deck[num] = tempArray
  }

  return deck
}

shuffleCards(cards)
